[package]
name = "triedb"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.8.21", features = ["arbitrary", "rand"] }
alloy-rlp = { version = "0.3.11", features = ["arrayvec"] }
alloy-trie = { version = "0.7.6", features=["arbitrary", "ethereum"]}
log = "0.4.25"
either = "1.14.0"
memmap2 = "0.9.5"
proptest = "1.6.0"
proptest-derive = "0.5.1"
sealed = "0.6.0"
pprof = { version = "0.14", features = ["criterion", "protobuf-codec"] }

[dev-dependencies]
criterion = "0.5"
tempdir = "0.3.7"
rand = "0.8.5"

[[bench]]
name = "database_benchmarks"
harness = false

[profile.bench]
debug = true
