name: PR

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
  
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Format
      run: |
        cargo +nightly fmt --all -- --check
        if [ $? -ne 0 ]; then
          echo "::error::Formatting check failed. Please run 'make format' locally and commit the changes."
          cargo +nightly fmt --all -- --check
          exit 1
        fi
  
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
